"use client";

import React, { useState } from "react";
import { toast } from "sonner";
import { Search, Trash2, RefreshCw, Eye, FileText } from "lucide-react";
import { useApi, apiCall } from "@/components/useApi";
import { PageHeader, Badge, EmptyState, Spinner, ConfirmModal } from "@/components/ui";
import MarkdownContent from "@/components/MarkdownContent";
import Paginate from "@/components/Paginate";
import { formatDate } from "@/lib/utils";

type Report = {
  id: string;
  title: string;
  course: string;
  topic: string;
  status: string;
  wordCount: number;
  createdAt: string;
  updatedAt: string;
  owner: string;
  email: string;
  sections: { title?: string; heading?: string; content?: string }[];
};

type ReportsData = {
  reports: Report[];
  total: number;
  page: number;
  pages: number;
};

const statusColor: Record<string, string> = { published: "green", draft: "amber" };

export default function ReportsPage() {
  const [search, setSearch] = useState("");
  const [page, setPage] = useState(1);
  const params = new URLSearchParams();
  if (search) params.set("search", search);
  params.set("page", String(page));
  params.set("limit", "20");
  const { data, loading, refetch } = useApi<ReportsData>(`/api/admin/reports?${params.toString()}`);
  const [deleteTarget, setDeleteTarget] = useState<Report | null>(null);
  const [deleting, setDeleting] = useState(false);
  const [viewTarget, setViewTarget] = useState<Report | null>(null);

  const handleDelete = async () => {
    if (!deleteTarget) return;
    setDeleting(true);
    try {
      await apiCall(`/api/admin/reports/${deleteTarget.id}`, { method: "DELETE" });
      toast.success("Report deleted");
      setDeleteTarget(null);
      refetch();
    } catch (e) {
      toast.error((e as Error).message);
    } finally {
      setDeleting(false);
    }
  };

  return (
    <div>
      <PageHeader title="Reports" subtitle={`${data?.total ?? "…"} generated research reports`} />

      <div className="mb-4 flex flex-wrap items-center gap-3">
        <div className="tb-search min-w-56 flex-1">
          <Search className="h-3.5 w-3.5 shrink-0" />
          <input
            value={search}
            onChange={(e) => {
              setSearch(e.target.value);
              setPage(1);
            }}
            placeholder="Search reports…"
          />
        </div>
        <button onClick={refetch} className="tb-btn" aria-label="Refresh">
          <RefreshCw />
        </button>
      </div>

      <div className="panel">
        {loading ? (
          <div className="flex h-48 items-center justify-center">
            <Spinner />
          </div>
        ) : !data || data.reports.length === 0 ? (
          <EmptyState title="No reports found" subtitle="Reports generated by users will appear here." />
        ) : (
          <>
            <div className="table-wrap">
              <table className="min-w-[720px]">
                <thead>
                  <tr>
                    <th>Title</th>
                    <th>Course</th>
                    <th>Status</th>
                    <th>Words</th>
                    <th>Author</th>
                    <th>Created</th>
                    <th className="text-right">Actions</th>
                  </tr>
                </thead>
                <tbody>
                  {data.reports.map((r) => (
                    <tr key={r.id}>
                      <td className="max-w-72">
                        <p className="truncate font-medium text-ink">{r.title}</p>
                      </td>
                      <td>{r.course || "—"}</td>
                      <td>
                        <Badge color={statusColor[r.status] || "slate"}>{r.status}</Badge>
                      </td>
                      <td className="td-mono">{r.wordCount.toLocaleString()}</td>
                      <td>
                        <p className="text-ink">{r.owner}</p>
                        <p className="td-sub">{r.email}</p>
                      </td>
                      <td className="td-mono">{formatDate(r.createdAt)}</td>
                      <td>
                        <div className="flex justify-end gap-1">
                          <button
                            onClick={() => setViewTarget(r)}
                            className="tb-btn"
                            style={{ width: 30, height: 30, borderRadius: 8 }}
                            aria-label="View"
                          >
                            <Eye className="h-3.5 w-3.5" />
                          </button>
                          <button onClick={() => setDeleteTarget(r)} className="tb-btn" style={{ width: 30, height: 30, borderRadius: 8 }} aria-label="Delete">
                            <Trash2 className="h-3.5 w-3.5" />
                          </button>
                        </div>
                      </td>
                    </tr>
                  ))}
                </tbody>
              </table>
            </div>

            <Paginate
              page={data.page}
              pages={data.pages}
              count={data.total}
              onPage={setPage}
              label="reports"
            />
          </>
        )}
      </div>

      {viewTarget && (
        <div className="modal-overlay" onClick={() => setViewTarget(null)}>
          <div className="modal modal-view" onClick={(e) => e.stopPropagation()}>
            <div className="modal-head">
              <div className="flex min-w-0 items-center gap-3">
                <span className="view-icon">
                  <FileText className="h-4 w-4" />
                </span>
                <div className="min-w-0">
                  <h3 className="view-title truncate">{viewTarget.title}</h3>
                  <p className="view-sub">Report · {viewTarget.wordCount.toLocaleString()} words</p>
                </div>
              </div>
              <button onClick={() => setViewTarget(null)} className="modal-close" aria-label="Close">
                <span className="text-sm text-ink3">✕</span>
              </button>
            </div>
            <div className="modal-body max-h-[62vh] overflow-y-auto">
              <div className="view-badges mb-5">
                <span className="chip chip-acid">{viewTarget.status}</span>
                {viewTarget.course && <span className="chip">{viewTarget.course}</span>}
                {viewTarget.topic && <span className="chip">{viewTarget.topic}</span>}
                <span className="chip">by {viewTarget.owner || viewTarget.email}</span>
                <span className="chip">{formatDate(viewTarget.createdAt)}</span>
              </div>
              {viewTarget.sections && viewTarget.sections.length > 0 ? (
                <div className="space-y-4">
                  {viewTarget.sections.map((s, i) => (
                    <div key={i}>
                      {s.title || s.heading ? (
                        <p className="mb-1 text-sm font-semibold text-ink">{s.title || s.heading}</p>
                      ) : null}
                      {s.content ? <MarkdownContent>{s.content}</MarkdownContent> : null}
                    </div>
                  ))}
                </div>
              ) : (
                <p className="text-sm text-ink2">No content sections.</p>
              )}
            </div>
            <div className="modal-footer">
              <button onClick={() => setViewTarget(null)} className="btn-modal btn-modal-cancel">
                Close
              </button>
            </div>
          </div>
        </div>
      )}

      <ConfirmModal
        open={!!deleteTarget}
        title="Delete report"
        message={`This will permanently delete "${deleteTarget?.title}". This cannot be undone.`}
        loading={deleting}
        onConfirm={handleDelete}
        onCancel={() => setDeleteTarget(null)}
      />
    </div>
  );
}
